NOTE_OFF = 0x8
NOTE_ON = 0x9
CONTROL_CHANGE = 0xB
PROGRAM_CHANGE = 0xC
PITCH_BEND = 0xE
off = NOTE_OFF
on = NOTE_ON
pc = PROGRAM_CHANGE
cc = CONTROL_CHANGE
pb = PITCH_BEND

SUSTAIN_PEDAL = 0x40
sustain = SUSTAIN_PEDAL
