NOTE_OFF = 0x8
NOTE_ON = 0x9
POLY_PRESSURE = 0xA
CONTROL_CHANGE = 0xB
PROGRAM_CHANGE = 0xC
CHANNEL_PRESSURE = 0xD
PITCH_BEND = 0xE
off = NOTE_OFF
on = NOTE_ON
pp = POLY_PRESSURE
cc = CONTROL_CHANGE
pc = PROGRAM_CHANGE
cp = CHANNEL_PRESSURE
pb = PITCH_BEND

SUSTAIN_PEDAL = 0x40
sustain = SUSTAIN_PEDAL
